### ISSUE TITLE
Ciclo de vida del software_JudithReynaCruzSantiago

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-1-infografia-JudithReynaCS#2]
[Ciclo de vida del software_JudithReynaCruzSantiago.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-JudithReynaCS/files/9426192/Ciclo.de.vida.del.software_JudithReynaCruzSantiago.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
